### ISSUE TITLE
How to retrieve data?

### ISSUE THREAD

**Issue by jnehring** [dkt-projekt/e-Sesame#7]
I am using e-Sesame. The documentation it is unclear to me
- What does inputType=NIF do?
- Is there a way to control the output format of the service?
- No matter what I query, I always get this return:

```
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
        xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
        xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
        xmlns:foaf="http://xmlns.com/foaf/0.1/"
        xmlns:nif="http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#"
        xmlns:dbo="http://dbpedia.org/ontology/"
        xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos/"
        xmlns:time="http://www.w3.org/2006/time#">
```

I tried this, it is the example but with a non existing object - should give no return at all:

```
curl -X POST "http://dev.digitale-kuratierung.de/api/e-sesame/retrieveData?storageName=sesame2&inputDataFormat=triple&object=%3Chttp://dbpedia.org/ontology/Locationxxx%3E"
```

This is actually what I want: Give me all resources that are a nif:Context:

```
curl -X POST "http://dev.digitale-kuratierung.dsame/retrieveData?storageName=jan-test&inputDataFormat=triple&object=%3http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#Context%3E"
```

This curl here should retrieve all triples in the graph:

```
curl -X GET -H "Cache-Control: no-cache" -H "Postman-Token: 8c534412-00ae-2e41-5025-72ebe47290dc" "http://dev.digitale-kuratierung.de/api/e-sesame/retrieveData?storageName=jan-test&inputDataFormat=sparql&input=SELECT%2520%2524s%2520%2524p%2520%2524o%2520WHERE%2520%257B%2520%2524s%2520%2524p%2520%2524o%2520%257D"
```

Executing this SPARQL query:

```
SELECT $s $p $o WHERE { $s $p $o }
```

but it returns

```
{
  "exception": "eu.freme.common.exception.BadRequestException",
  "path": "/e-sesame/retrieveData",
  "message": "No text to process.",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1471359062981
}
```

**Comment by jmschnei** [comment]
I think that the problem is in the not encoding of the url of the entities. Then curl or postman has trouble in handling it. For example, in the case of looking for `http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#Context`, it should previously encoded and then it should be used `http%3A%2F%2Fpersistence.uni-leipzig.org%2Fnlp2rdf%2Fontologies%2Fnif-core%23Context`.

Another thing is that entity url should not contain the characters `<` and `>`.

I have tried the following CURL examples and they work:
1. For the case of looking for Context:

> curl -X POST -d '' "http://dev.digitale-kuratierung.de/api/e-sesame/retrieveData?storageName=jan-test&inputDataFormat=triple&object=http%3A%2F%2Fpersistence.uni-leipzig.org%2Fnlp2rdf%2Fontologies%2Fnif-core%23Context&outformat=text/turtle"
1. For the case of using SPARQL queries, it must be specified the parameter `informat=text/plain` together with the `inputDataFormat=sparql`. I have tried the next query to retrieve all the triples of a graph:

> curl -X POST -d '' "http://dev.digitale-kuratierung.de/api/e-sesame/retrieveData?storageName=jan-test&inputDataFormat=sparql&input=SELECT%20%24s%20%24p%20%24o%20WHERE%20%7B%20%24s%20%24p%20%24o%20%7D&informat=text/plain"

In the case of the SPARQL query, the output is always XML.

**Comment by jnehring** [comment]
Thank you. Is there a reason why you used POST requests? I think a GET requests works also. I put both examples in the documentation and deleted the old, not working example.

It is still unclear what inputDataForm=NIF does. I suggest to either doucment it properly or remove it from the documentation.
